### PR TITLE
feat: add relations from common

### PR DESCRIPTION
**Pull request by everpcpc**
- needs: https://github.com/bangumi/common/pull/4
- fixes: #793
- needs: https://github.com/bangumi/common/pull/7

### CODE REVIEW

**Comment by everpcpc** [comment]
@trim21  PTAL

**Comment by everpcpc** [comment]
那我先把 network service 的部分单独拿出来另开一个 pr 吧

**Comment by trim21** [comment]
原本的platform是不是应该删掉？

**Comment by everpcpc** [comment]
删掉了

**Pull request merged**
